# Generated by Django 4.2.25 on 2025-11-24 06:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('discord', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='GRIVYZOM', max_length=200)),
                ('subtitle', models.CharField(default='A WORLD OF ADVENTURE AND CREATIVITY', max_length=300)),
                ('button_text', models.CharField(default='JUGAR AHORA!', max_length=100)),
                ('image', models.ImageField(upload_to='game_header_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Game Header',
                'verbose_name_plural': 'Game Headers',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('role', models.CharField(choices=[('DEFAULT', 'Default'), ('USUARIO', 'Usuario'), ('APRENDIZ', 'Aprendiz'), ('MIEMBRO', 'Miembro'), ('VETERANO', 'Veterano'), ('VIP', 'VIP'), ('VIP_PLUS', 'VIP+'), ('STREAMER', 'Streamer'), ('HELPER', 'Helper'), ('BUILDER', 'Builder'), ('MODERADOR', 'Moderador'), ('ADMIN', 'Admin'), ('DEVELOPER', 'Developer')], default='DEFAULT', max_length=20, verbose_name='Rol')),
                ('discord_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario de Discord')),
                ('minecraft_username', models.CharField(help_text='Nombre de usuario en Minecraft (3-16 caracteres)', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Usuario de Minecraft')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Biografía')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último inicio de sesión')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Baneado')),
                ('ban_reason', models.TextField(blank=True, null=True, verbose_name='Razón del baneo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
