# Generated by Django 4.2.25 on 2025-11-25 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Banner')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagen del Banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='active_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.banner', verbose_name='Banner Activo'),
        ),
        migrations.AddField(
            model_name='user',
            name='collected_banners',
            field=models.ManyToManyField(blank=True, related_name='collectors', to='core.banner', verbose_name='Banners Coleccionados'),
        ),
    ]
