# Generated by Django 4.2.25 on 2025-11-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_user_active_banner_user_collected_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración de Token de Restablecimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de Restablecimiento de Contraseña'),
        ),
    ]
