# Generated by Django 4.2.25 on 2025-12-20 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase CSS del icono (ej: ci-Camera)', max_length=50, verbose_name='Icono CSS')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Galería',
                'verbose_name_plural': 'Categorías de Galería',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagen')),
                ('thumbnail', models.ImageField(blank=True, help_text='Se genera automáticamente si no se proporciona', null=True, upload_to='gallery/thumbnails/', verbose_name='Miniatura')),
                ('author', models.CharField(blank=True, help_text='Nombre del jugador o builder', max_length=100, verbose_name='Autor')),
                ('is_featured', models.BooleanField(default=False, help_text='Las imágenes destacadas aparecen primero', verbose_name='Destacada')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallerycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
    ]
