# Generated by Django 4.2.25 on 2025-12-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gallerycategory_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password_hash', models.CharField(help_text='Contraseña hasheada con Django', max_length=128, verbose_name='Contraseña (hash)')),
                ('verification_code', models.CharField(help_text='Código de 6 caracteres alfanuméricos (ej: A7X9K2)', max_length=6, unique=True, verbose_name='Código de Verificación')),
                ('minecraft_uuid', models.CharField(blank=True, help_text='Se llena cuando el jugador verifica en Minecraft', max_length=36, null=True, verbose_name='UUID de Minecraft')),
                ('minecraft_username_verified', models.CharField(blank=True, help_text='Nombre en Minecraft del jugador que verificó', max_length=16, null=True, verbose_name='Username Minecraft Verificado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFIED', 'Verificado'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(help_text='El código expira después de 15 minutos', verbose_name='Fecha de Expiración')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se solicitó el registro', null=True, verbose_name='Dirección IP')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Número de intentos fallidos de verificación', verbose_name='Intentos de Verificación')),
            ],
            options={
                'verbose_name': 'Registro Pendiente',
                'verbose_name_plural': 'Registros Pendientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='minecraft_uuid',
            field=models.CharField(blank=True, help_text='UUID del jugador en Minecraft (ej: 550e8400-e29b-41d4-a716-446655440000)', max_length=36, null=True, unique=True, verbose_name='UUID de Minecraft'),
        ),
    ]
