# Generated by Django 4.2.25 on 2025-12-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pendingregistration_user_minecraft_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='auth_token',
            field=models.CharField(blank=True, help_text='Token de un solo uso para auto-login después de verificar', max_length=128, null=True, unique=True, verbose_name='Token de Auto-Login'),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='auth_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del Token'),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='auth_token_used',
            field=models.BooleanField(default=False, verbose_name='Token Usado'),
        ),
    ]
