# Generated by Django 4.2.25 on 2025-12-21 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pendingregistration_auth_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Slug URL')),
                ('excerpt', models.CharField(blank=True, help_text='Resumen corto del post (máx 300 caracteres)', max_length=300, verbose_name='Extracto')),
                ('content', models.TextField(help_text='Contenido del post en formato Markdown', verbose_name='Contenido (Markdown)')),
                ('cover_image', models.ImageField(blank=True, help_text='Resolución recomendada: 1920x1080', null=True, upload_to='community/covers/%Y/%m/', verbose_name='Imagen de Portada')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Lista de etiquetas sin #', verbose_name='Etiquetas')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado'), ('HIDDEN', 'Oculto'), ('DELETED', 'Eliminado')], default='PUBLISHED', max_length=20, verbose_name='Estado')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fijado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post de Comunidad',
                'verbose_name_plural': 'Posts de Comunidad',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, default='folder', help_text='Nombre del icono Lucide (ej: hammer, book-open, trophy)', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='#8b5cf6', help_text='Color hexadecimal (ej: #8b5cf6)', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Post',
                'verbose_name_plural': 'Categorías de Posts',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='Contenido')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.communitypost')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='communitypost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.postcategory', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marcador',
                'verbose_name_plural': 'Marcadores',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['status', '-created_at'], name='core_commun_status_7eb7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['author', '-created_at'], name='core_commun_author__9522d6_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['category', '-created_at'], name='core_commun_categor_035ea9_idx'),
        ),
    ]
