# Generated by Django 4.2.25 on 2025-12-21 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_communitypost_postcategory_postcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='minecraft_username',
            field=models.CharField(blank=True, help_text='Nombre de usuario en Minecraft (3-16 caracteres)', max_length=16, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Usuario de Minecraft'),
        ),
    ]
