# Generated by Django 4.2.25 on 2025-12-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_allow_null_minecraft_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameheader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_header_images/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
