# Generated by Django 4.2.25 on 2025-12-27 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_gameheader_image_alter_herosection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('product_type', models.CharField(choices=[('rank', 'Rango'), ('cosmetic', 'Cosmético'), ('crate', 'Caja'), ('feature', 'Función'), ('item', 'Item')], max_length=20, verbose_name='Tipo de Producto')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono Lucide (ej: crown, sparkles, box)', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='#8b5cf6', help_text='Color hexadecimal (ej: #8b5cf6)', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto (ej: VIP+, Partículas de Fuego)', max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(help_text='Descripción completa del producto en Markdown', max_length=1000, verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, help_text='Resumen breve para listados', max_length=200, verbose_name='Descripción Corta')),
                ('product_type', models.CharField(choices=[('rank', 'Rango'), ('cosmetic', 'Cosmético'), ('crate', 'Caja'), ('feature', 'Función'), ('item', 'Item')], max_length=20, verbose_name='Tipo de Producto')),
                ('image', models.ImageField(help_text='Resolución recomendada: 800x800px (max 5MB)', upload_to='products/%Y/%m/', verbose_name='Imagen del Producto')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en la moneda del servidor', max_digits=10, verbose_name='Precio')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacío si no hay descuento', max_digits=10, null=True, verbose_name='Precio con Descuento')),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], default='common', max_length=20, verbose_name='Rareza')),
                ('is_available', models.BooleanField(default=True, help_text='Si está disponible para compra', verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, help_text='Aparece en la sección destacada', verbose_name='Destacado')),
                ('is_new', models.BooleanField(default=False, help_text='Marca el producto como nuevo', verbose_name='Nuevo')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Cantidad disponible (vacío = ilimitado)', null=True, verbose_name='Stock')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('type_specific_data', models.JSONField(blank=True, default=dict, help_text='Campos adicionales según el tipo de producto', verbose_name='Datos Específicos del Tipo')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('purchases', models.PositiveIntegerField(default=0, verbose_name='Compras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_modified', to=settings.AUTH_USER_MODEL, verbose_name='Última Modificación Por')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-is_featured', 'order', '-created_at'],
                'indexes': [models.Index(fields=['product_type', 'is_available'], name='core_produc_product_6a5fe9_idx'), models.Index(fields=['category', '-created_at'], name='core_produc_categor_afffb1_idx'), models.Index(fields=['-is_featured', 'order'], name='core_produc_is_feat_8cb3ce_idx')],
            },
        ),
    ]
