# Generated by Django 4.2.25 on 2025-12-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productcategory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Descripción Corta')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('category', models.CharField(choices=[('pvp', 'PvP'), ('evento', 'Evento'), ('actualizacion', 'Actualización'), ('torneo', 'Torneo'), ('construccion', 'Construcción'), ('comunidad', 'Comunidad')], max_length=20, verbose_name='Categoría')),
                ('status', models.CharField(choices=[('upcoming', 'Próximo'), ('ongoing', 'En Curso'), ('completed', 'Finalizado'), ('cancelled', 'Cancelado')], default='upcoming', max_length=20, verbose_name='Estado')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='Banner')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='events/cards/', verbose_name='Imagen de Tarjeta')),
                ('color', models.CharField(blank=True, help_text='Color hexadecimal (ej: #ff0000)', max_length=7, verbose_name='Color Personalizado')),
                ('prizes', models.JSONField(blank=True, default=list, help_text='Lista de premios en formato JSON', verbose_name='Premios')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación/Servidor')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Participantes')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Participantes Actuales')),
                ('requires_registration', models.BooleanField(default=False, verbose_name='Requiere Inscripción')),
                ('registration_url', models.URLField(blank=True, verbose_name='URL de Inscripción')),
                ('grovs_reward', models.PositiveIntegerField(default=0, verbose_name='Recompensa en Grovs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
