"""
Django settings for backendGrivyzom project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
DOTENV_PATH = BASE_DIR / '.env'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Parse ALLOWED_HOSTS from comma-separated string
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Configuración de proxy reverso (nginx/Cloudflare)
# Permite que Django use el host original del request
USE_X_FORWARDED_HOST = True
# Permite que Django detecte HTTPS a través del header de proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Configuración de CORS para permitir credenciales (sesiones)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://138.68.51.86:4200",
    "https://grivyzom.com",
    "https://www.grivyzom.com",
    "https://foro.grivyzom.com",
]


CORS_ALLOW_CREDENTIALS = True  # IMPORTANTE: Permite enviar cookies de sesión
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Métodos HTTP permitidos para CORS
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
    "https://grivyzom.com",
    "https://www.grivyzom.com",
    "https://api.grivyzom.com",
    "https://foro.grivyzom.com",
]

# Configuración de cookies de sesión para producción con CORS cross-origin
SESSION_COOKIE_SAMESITE = 'None'  # None para permitir cross-origin (REQUIERE Secure=True)
SESSION_COOKIE_SECURE = not DEBUG  # True en producción (HTTPS), False en desarrollo
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24 horas

# Configuración de cookies CSRF para producción con CORS cross-origin
CSRF_COOKIE_SAMESITE = 'None'  # None para permitir cross-origin
CSRF_COOKIE_SECURE = not DEBUG  # True en producción (HTTPS), False en desarrollo
CSRF_COOKIE_HTTPONLY = False  # False para que JavaScript pueda leerla



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backendGrivyzom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backendGrivyzom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'OPTIONS': {
            'init_command': "SET default_storage_engine=INNODB",
        }
    },
    'minecraft': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('MINECRAFT_DB_NAME'),
        'USER': config('MINECRAFT_DB_USER'),
        'PASSWORD': config('MINECRAFT_DB_PASSWORD'),
        'HOST': config('MINECRAFT_DB_HOST'),
        'PORT': config('MINECRAFT_DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
# Configuración eliminada - ver línea 225 para la configuración completa con min_length


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Configuración de sesiones
SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Password validators personalizados
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Límite de intentos de login (recomendado usar django-ratelimit en producción)
# Para desarrollo, las validaciones están en las vistas

# ============================================================================
# MINECRAFT PLUGIN INTEGRATION
# ============================================================================
# API Key para autenticar requests del plugin de Minecraft
# IMPORTANTE: Esta key debe mantenerse secreta y solo conocida por el plugin
MC_PLUGIN_API_KEY = config('MC_PLUGIN_API_KEY', default=None)

# Tiempo de expiración de registros pendientes (en minutos)
PENDING_REGISTRATION_EXPIRY_MINUTES = config('PENDING_REGISTRATION_EXPIRY_MINUTES', default=15, cast=int)

# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@grivyzom.com')

# Frontend URL for password reset links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:4200')
